### ISSUE TITLE
Error to get channel endpoint: Error Domain=com.amazonaws.AWSCognitoIdentityErrorDomain Code=8 "(null)"

### ISSUE THREAD

**Issue by pankeshpatel** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios#23] opened 2020-12-07 07:16 UTC
Hi all,

I have followed the step, suggested on page [WebRTC SDK for iOS](https://docs.aws.amazon.com/kinesisvideostreams-webrtc-dg/latest/devguide/kvswebrtc-sdk-ios.html). I have configured Cognito userpool and Cognito IdentiyPool as follows:

1. "Enable access to unauthenticated identities" is checked under "Unauthenticated identities" in Identity Pool setting.
2.  Edited the Trust Relationship for unauth role in IAM to and retry (suggested [here](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios/issues/8) )

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Federated": "cognito-identity.amazonaws.com"
      },
      "Action": "sts:AssumeRoleWithWebIdentity"
    }
  ]
}
```
However, I am getting the following error

`Error to get channel endpoint: Error Domain=com.amazonaws.AWSCognitoIdentityErrorDomain Code=8 "(null)" UserInfo={__type=NotAuthorizedException, message=Identity pool - us-east-1:XXXX-XXX-XXX-XXX-XXXXX does not have identity providers configured.`

**Comment by MushMal** [comment] 2020-12-07 07:23
Unauthenticated access is not supported. We are looking at it but no definitive dates

**Comment by pankeshpatel** [comment] 2020-12-07 07:32
Thanks @MushMal  for the advice!  I understand that the team has been working on this and the support has not been implemented yet.  However, just for testing/demo, How can I temporarily address this issue. 

Please advise!

**Comment by MushMal** [comment] 2020-12-07 07:35
There is no straight forward way with unauthenticated users. Try to use auth

**Comment by pankeshpatel** [comment] 2020-12-07 07:45
@MushMal Thanks for the advice!  
I have been using as "authorized user" ?(meaning that authorized user login first, then connect as master/viewer).  
Are you suggesting the same? and Are you suggesting make any modification in code?

**Comment by MushMal** [comment] 2020-12-07 18:26
Sorry for the delay. I am not sure what you mean entirely. The instructions in the readme step-by-step configuration. We have not had any issues related to Cognito auth.

**Comment by unicornss** [comment] 2020-12-08 16:49
@pankeshpatel  

- Can you check the AWS console for Cognito Identity Pool and click 
   -    `Edit Identity Pool -> Authentication Providers. `
- Confirm if  authentication providers are configured correctly.

**Comment by pankeshpatel** [comment] 2020-12-09 09:36
@unicornss : Thanks for the response.  

I have not configured any authentication providers in Identity Pool. 
Do you want me to configured any authentication providers to resolve this error?

**Comment by MushMal** [comment] 2020-12-09 09:43
@pankeshpatel there is a step-by-step instruction in the readme how to configure Cognito. Please follow those and if you have any issues with Cognito re-open this issue.

Please go ahead and resolve this

**Comment by pankeshpatel** [comment] 2020-12-09 09:58
@MushMal : my Cognito configurations work perfectly. We have our own iOS app (which works perfectly) without having any configuration in `Authentication Providers` of `Identity Pool`.  So, I do not think so that there is any issue in `Authentication Providers` configuration. 

@MushMal: I have been still getting the same error, after following the readme guide ;)

**Comment by MushMal** [comment] 2020-12-09 10:03
Not sure what could be the issue. The sample is tested in a specific scenario only. I would like others to chime in if they have any issues related to Cognito configuration. @unicornss @dswamina I am looking for some guidance in this case. If the issue is reproducible with stock application and the custom is following the instructions step-by-step then I am not sure what's wrong with Cognito.

**Comment by unicornss** [comment] 2020-12-09 15:27
@MushMal  Sure, will check if any thing has changed recently.

**Comment by dswamina** [comment] 2020-12-29 22:26
Can you try using this documentation - https://docs.aws.amazon.com/kinesisvideostreams-webrtc-dg/latest/devguide/kvswebrtc-sdk-ios.html under the heading "Configure Amazon Cognito for the iOS WebRTC SDK". 

Might be possibly related to this as well- https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios/issues/24

**Comment by hassanctech** [comment] 2021-02-15 21:53
@pankeshpatel did the suggestion from @dswamina work for you?  If so, please go ahead and close this issue.

**Closed** 2021-02-15 22:02 UTC
Labels: question
