### ISSUE TITLE
WebRTC does not connect if there is no forced delay between Signaling Client connect and sendOffer

### ISSUE THREAD

**Issue by bijuC1983** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios#32] opened 2021-03-02 12:36 UTC
`signalingClient!.connect()

        let seconds = 2.0
        DispatchQueue.main.asyncAfter(deadline: .now() + seconds) {
            self.updateConnectionLabel()
            self.vc = VideoViewController(webRTCClient: self.webRTCClient!, signalingClient: self.signalingClient!, localSenderClientID: self.localSenderId, isMaster: self.isMaster!)
            self.present(self.vc!, animated: true, completion: nil)
        }`

As you see in the above snippet there is a delay of 2 seconds after the connect method is executed and before the sendOffer is executed inside VideoViewController init method.
If this is set to 0, the WebRTC does not get connected and for values between 0 & 2 it is very inconsistent. Even with 2, one or two out of ten times it does not get connected.
- This [file](https://drive.google.com/file/d/1wcxio8nXeKH9jPE0IV3NXrcU9zXP1eB-/view?usp=sharing) has the log when the forced delay was set to 0 seconds. WebRTC does not connect with this. It tries to connect for a minute after which, the connection is closed by a timer in the application.
- This [file](https://drive.google.com/file/d/19w7Gg6MpUJo-lnSu6UZS6-yrKBTInM2N/view?usp=sharing) has the log when forced delay was set to 2 seconds. WebRTC connects successfully.

What is the significance of this delay and how could this be made more consistent? This is not something specific to an individual network because these findings are from beta testing with an audience of 30+ people.

Thanks in advance.

**Comment by disa6302** [comment] 2021-03-04 21:05
@bijuC1983 , 

This is what happens in the SDK: 
Without the delay, the async call executes instantly, and the `socket.write` in [sendOffer](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios/blob/42be6a24ef7d8129a21afdb6e02b6d717d31b475/Swift/KVSiOSApp/SignalingClient.swift#L37) returns because socket is no connected yet. Hence, offer is also not sent. By the time the connection is established, ICE candidates get sent anyways but we miss the bus to send the offer here because we technically need to wait for connection to be established. Hence connection is not established. The sample has the delay that works for most of the cases and we can confirm it works even with 0.5s in our testing. You can tune this delay to suit your use case and network condition.

**Comment by disa6302** [comment] 2021-03-05 00:24
The sample accounts for the time it needs to establish the connection before bring up the video view, 
but you could try launching that view after [this]( https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios/blob/eca0d651f09b3716cfb37aa787435e14e1c2f1ae/Swift/KVSiOSApp/SignalingClient.swift#L80) triggers

**Comment by bijuC1983** [comment] 2021-03-10 13:23
Hello @disa6302 
Thank you for your suggestions. I am now using the signalClientDidConnect to launch the view.
The consistency has improved and the initialisation time has decreased.
However, 2 scenarios were noticed:
1. 1 out of 10 times, signalClientDidConnect is not called and the sequence gets stalled after that resulting in WebRTC connection not getting established. The log for this scenario is here
2. 1 out of 10 times, signallingClientDidConnect is called and also .connected is received in didChangeConnectionState for webRTCClient. But, no video is received from the master. The log for this scenario is here
Could you share your inputs regarding what could be happening in the above 2 scenarios and what are the ways the above could be avoided/fixed/handled?

**Comment by disa6302** [comment] 2021-03-11 20:49
@bijuC1983 , 

For the first issue, you can look into using a timeout in the starscream client to allow user to get the option to reconnect.
For the second issue, I did go through the logs but did not find any errors. Can you provide the SDP offer and answer and also  let us know if you see any errors in this case?

**Comment by bijuC1983** [comment] 2021-03-15 11:00
@disa6302 Thank your for your suggestions and inputs

- For the first issue, as per your suggestion we have set a timeout of 5 seconds for starscream web socket. I had set it to less than a second for test purposes and found out that signalClientDidDisconnect is called on timeout. Inside that callback I am connecting the socket (socket.connect()) again if max retry count was not exceeded. We are currently testing if this retry mechanism works, however, in the last couple of hours this scenario has not taken place yet. I understand that this is more of Starscream question but based on your experience would you suggest doing anything differently?
- We have merged the commit 42be6a24ef7d8129a21afdb6e02b6d717d31b475 into our code and not sure it is related but in the last couple of hours of testing, issue 2 has also not occurred yet to capture the SDP offer and answer. I have released the app to more internal testers and shall keep you updated.

Thanks again!

**Comment by disa6302** [comment] 2021-03-15 19:25
@bijuC1983 , 

I do not think I would do anything differently for the first case.

**Comment by disa6302** [comment] 2021-03-18 16:30
@bijuC1983 ,

I am closing this issue for now since the question is answered. Feel free to open a new issue if you reproduce the issue. Would like to minimize the scope of this ticket to the original question

**Closed by disa6302** 2021-03-18 16:30 UTC
