### ISSUE TITLE
No such module 'AWS CognitoIdentityProvider'

### ISSUE THREAD

**Issue by hho114** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios#19] opened 2020-10-14 18:00 UTC
Swift Compiler Error message: No such module 'AWS CognitoIdentityProvider'

Hi, I want to try the Kinesis Video Stream sample for ios. when I try to build the app, I got this error. I have been removed Pods dir and rerun pod install multiple times and still get the same error. I really appreciate any help. Thank you

System Info:
Xcode version: 12.0.1
pod version: 1.9.3

**Comment by sb28103** [comment] 2020-11-05 14:22
@hho114 - I had this same issue when trying to run on the simulator. Running on device with only building active architectures resolved the issue for me.

**Comment by MushMal** [comment] 2020-11-05 20:10
Apologies for delay in these. Many of these build questions can not be directly answered by the support team as they might not be able to reproduce.

Is this issue happening? Can this issue be closed?

**Comment by sb28103** [comment] 2020-11-05 20:37
No worries @MushMal - I just had this issue this morning with XCode 12 - not a blocker on device, but if you want folks to run on a simulator is seems to be a real issue. I'm not blocked, thanks for the reply.

**Comment by MushMal** [comment] 2020-11-05 20:41
@dswamina have we encountered any issues related to Cognito provider not being found on the emulator? Sounds odd really.

**Comment by sb28103** [comment] 2020-11-05 20:42
@MushMal - it seemed to have issues with the Pods in general not just Cognito

**Comment by codingspirit** [comment] 2020-12-24 07:37
I met the exactly same issue here. Is there anyone successfully build and run with emulator?

**Comment by dswamina** [comment] 2020-12-28 18:28
Yes, the application is currently not working on the simulator. We have plans to fix this but it should work as needed on the physical device. Can you also please give me information on what the iOS version you're running the application (with the simulator) ? I understand XCode 12 is the one you're using to build.

**Comment by codingspirit** [comment] 2021-01-05 01:15
> Yes, the application is currently not working on the simulator. We have plans to fix this but it should work as needed on the physical device. Can you also please give me information on what the iOS version you're running the application (with the simulator) ? I understand XCode 12 is the one you're using to build.

XCode 12. BTW, I can build it successfully with emulator if I create a new project and install dependencies with pod. There might be something wrong in [current project file](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-ios/blob/master/Swift/AWSKinesisVideoWebRTCDemoApp.xcodeproj/project.pbxproj)

**Comment by brendonparker** [comment] 2021-01-30 14:45
I'm having the same problem. Also, can't even get it to compile targeting my local device.
Using XCode 12.4

**Comment by MushMal** [comment] 2021-01-31 00:34
Are we actually having an issue here still? Can we resolve this? Sorry, I don't have the latest info here.

**Comment by brendonparker** [comment] 2021-01-31 01:52
The issue is you can’t run it on a simulator, I’m not sure how valid of a use case that is anyways, since it needs camera access.

**Comment by MushMal** [comment] 2021-01-31 01:55
Thanks for confirming, this was my understanding too. To iterate:

**The current iOS WebRTC SDK (this project) can't run in the emulator**

This is a known issue still and will be resolved in the priority order. However, as an open source repository we are welcoming any contribution - including investigations.

**Comment by brendonparker** [comment] 2021-01-31 01:57
Sounds right. I spent some time looking at it, but super new to swift/iOS (more of a .NET guy) and didn’t figure it out.

 @codingspirit may have been closer. Perhaps he can share his new project file that supposedly worked.

**Comment by disa6302** [comment] 2021-08-02 07:13
Closing since the issue is stale.

**Closed by disa6302** 2021-08-02 07:13 UTC
Labels: build
